[versions]
kotlin = "2.2.21"
springframework-boot = "4.0.2"
spring-dependency-management = "1.1.7"
datafaker = "2.5.3"

[libraries]
datafaker = { module = "net.datafaker:datafaker", version.ref = "datafaker" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
springframework-boot = { id = "org.springframework.boot", version.ref = "springframework-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
